### ISSUE TITLE
 "random_string" prints sensitive data to console

### ISSUE THREAD

**Issue by idevchris** [terraform-providers/terraform-provider-random#17]
"random_string"uses the generated random string as id. The id will be printed to the console like "random_string.password: Refreshing state... (ID: s**********)" when executing `terraform plan`.  If you want to use an random_string as an password, you won't like your sensitive data printed to the console.

### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.0.1
+ provider.random v1.1.0

### Affected Resource(s)
- provider.random

### Expected Behavior
random string should not use the result as id, because it could be sensitive data and will be output when running terraform plan: "random_string.password: Refreshing state... (ID: s**********)"

### Actual Behavior
random string uses the result as id and outputs it when running "terraform plan"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a "random_string"
2. `terraform plan`

**Comment by danmerron-sig** [comment]
I've raised a PR to add an additional option to the provider `random_password` which is essentially a code duplication of `random_password` but hides the output using the method shown in #18. 

Feedback appreciated 👍

**Comment by simonclausen** [comment]
Having a separate `random_password` provider sounds like the best option to me. While I'm also looking for generating private strings with terraform for passwords, in some cases it's convenient to have the string output right there in the console.

**Comment by Bharathkumarraju** [comment]
when this will be released ...below one currently not working for me.

```
resource "random_password" "db_password" {
  length = 16
  special = true
  override_special = "!#()-[]<>"
}

resource "aws_db_instance" "bharaths_mysql" {
  instance_class = "db.t2.micro"
  identifier_prefix = "bharaths-terraform-up-and-running"
  engine = "mysql"
  allocated_storage = 10
  name = "bharaths_example_database"
  username = "bharath_admin"
  skip_final_snapshot     =  true
  apply_immediately = true
  password = random_password.db_password.result
  lifecycle {
    ignore_changes = ["password"]
  }
}
```
