### ISSUE TITLE
random_string does not default to `special = false`

### ISSUE THREAD

**Issue by dmikalova** [terraform-providers/terraform-provider-random#6]
### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
random_string

### Terraform Configuration Files
```hcl
resource "random_string" "main" {
  length  = 4
}
```

### Expected Behavior
According to the [random_string docs](https://www.terraform.io/docs/providers/random/r/string.html) the argument `special` defaults to false.

### Actual Behavior
The above config created the string `!AA&` which has special characters in it.

**Comment by clstokes** [comment]
Docs are fixed in https://github.com/terraform-providers/terraform-provider-random/pull/7.

**Comment by radeksimko** [comment]
Thanks for the ping @clstokes , closing...
